user root;

worker_processes 1;

pid /var/snap/platform/common/log/nginx_custom_proxy.pid;
error_log syslog:server=unix:/dev/log warn;

events {
    worker_connections 256;
}

http {
    server_names_hash_bucket_size 64;
    access_log syslog:server=unix:/dev/log;

    client_body_temp_path /var/snap/platform/current/nginx/custom_proxy_client_body_temp;
    proxy_temp_path /var/snap/platform/current/nginx/custom_proxy_proxy_temp;
    fastcgi_temp_path /var/snap/platform/current/nginx/custom_proxy_fastcgi_temp;
    uwsgi_temp_path /var/snap/platform/current/nginx/custom_proxy_uwsgi_temp;
    scgi_temp_path /var/snap/platform/current/nginx/custom_proxy_scgi_temp;

    client_max_body_size 10G;
    proxy_send_timeout 600s;
    proxy_read_timeout 600s;
    proxy_buffering off;

    server {
        listen unix:/var/snap/platform/current/custom-proxy.socket;
        root /snap/platform/current/config/errors;
        error_page 502 /502.html;
        location = /502.html {
            internal;
        }
        location / {
            return 502;
        }
    }
{{range .Entries}}
    server {
        listen unix:/var/snap/platform/current/custom-proxy.socket;
        server_name {{.ServerName}};
{{if .Authelia}}
        location /internal/authelia/authz {
            internal;
            proxy_pass http://unix:/var/snap/platform/current/authelia.socket:/api/authz/auth-request;
            proxy_set_header X-Original-Method $request_method;
            proxy_set_header X-Original-URL https://$http_host$request_uri;
            proxy_set_header X-Forwarded-Proto https;
            proxy_set_header X-Forwarded-Host $http_host;
            proxy_set_header X-Forwarded-Uri $request_uri;
            proxy_set_header X-Forwarded-Ssl on;
            proxy_set_header X-Forwarded-For $remote_addr;
            proxy_set_header Content-Length "";
            proxy_set_header Connection "";
        }
{{end}}
        location / {
            if ($http_x_syncloud_custom_proxy) {
                return 502;
            }
{{if .Authelia}}
            auth_request /internal/authelia/authz;
            auth_request_set $redirection_url $upstream_http_location;
            auth_request_set $user $upstream_http_remote_user;
            auth_request_set $groups $upstream_http_remote_groups;
            auth_request_set $name $upstream_http_remote_name;
            auth_request_set $email $upstream_http_remote_email;
            proxy_set_header Remote-User $user;
            proxy_set_header Remote-Groups $groups;
            proxy_set_header Remote-Name $name;
            proxy_set_header Remote-Email $email;
            error_page 401 =302 $redirection_url;
{{end}}
            proxy_set_header X-Syncloud-Custom-Proxy "1";
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $http_host;
            proxy_pass {{.Scheme}}://{{.Host}}:{{.Port}};
        }
    }
{{end}}
}
