platform: ${platform}

clone:
  git:
    image: ${git}
    depth: 50

pipeline:
  build:
    image: syncloud/platform-build-deps-${arch}
    commands:
      - VERSION=$(date +%y%m%d)
      - ./build.sh $VERSION
      - ./unit-test.sh
      - ./test/js/runner/run.sh

  integration:
    image: syncloud/platform-build-deps-${arch}
    commands:
      - VERSION=$(date +%y%m%d)
      - NAME=platform${separator}$${VERSION}${separator}${installer_arch}.${installer_ext}
      - ./integration/test-docker.sh teamcity@syncloud.it password teamcity $NAME ${installer_version} master ${integration_test} ${installer} device

  upload:
    image: syncloud/platform-build-deps-${arch}
    secrets: [AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY]
    commands:
      - VERSION=$(date +%y%m%d)
      - ./upload.sh $DRONE_BRANCH $VERSION
    when:
      matrix:
        installer: sam

  ci-artifact:
    image: syncloud/platform-build-deps-${arch}
    secrets: [ARTIFACT_SSH_KEY]
    commands:
      - ./upload-artifact.sh integration/log $DRONE_BUILD_NUMBER-${installer}-${arch}
      - ./upload-artifact.sh integration/screenshot $DRONE_BUILD_NUMBER-${installer}-${arch}
    when:
      status: [ failure, success ] 

services:
  device:
    image: syncloud/systemd-${arch}
    privileged: true
    volumes:
      - /var/run/dbus:/var/run/dbus
 
matrix:
  include:
    - platform: linux/arm
      git: syncloud/armhf-drone-git
      arch: armhf
      installer: sam
      installer_version: 89
      installer_arch: armv7l
      installer_ext: tar.gz
      separator: "-"
      integration_test: verify
      
    - platform: linux/amd64
      git: plugins/git
      arch: amd64
      installer: sam
      installer_version: 89
      installer_arch: x86_64
      installer_ext: tar.gz
      separator: "-"
      integration_test: all

    - platform: linux/arm
      git: syncloud/armhf-drone-git
      arch: armhf
      installer: snapd
      installer_version: 170523
      installer_arch: armhf
      installer_ext: snap
      separator: _
      integration_test: verify

    - platform: linux/amd64
      git: plugins/git
      arch: amd64
      installer: snapd
      installer_version: 170523
      installer_arch: amd64
      installer_ext: snap
      separator: _
      integration_test: all