#!/snap/platform/current/python/bin/python

import os, sys
sys.path.append(os.path.join(os.environ['SNAP'], 'hooks'))

from installer import PlatformInstaller
platform_installer = PlatformInstaller()
platform_installer.install()