#!/snap/platform/current/python/bin/python

from syncloud_platform.installer import PlatformInstaller

import logging
from syncloud_app import logger

logger.init(logging.DEBUG, console=True, line_format='%(message)s')

platform_installer = PlatformInstaller()
platform_installer.post_refresh()