#!/snap/platform/current/python/bin/python

import os, sys
sys.path.append(os.path.join(os.environ['SNAP'], 'hooks'))

from installer import PlatformInstaller

import logging
from syncloud_app import logger

logger.init(logging.DEBUG, console=True, line_format='%(message)s')

platform_installer = PlatformInstaller()
platform_installer.install()