// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Confirmation: typeof import('./src/components/Confirmation.vue')['default']
    Dialog: typeof import('./src/components/Dialog.vue')['default']
    Error: typeof import('./src/components/Error.vue')['default']
    Menu: typeof import('./src/components/Menu.vue')['default']
    Notification: typeof import('./src/components/Notification.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
