serverAddr = "{{ .Server }}"
serverPort = 443
transport.tls.enable = true
metadatas.token = "{{ .Token }}"
webServer.unixSocket = "{{ .AdminSocket }}"

[[proxies]]
name = "{{ .Domain }}"
type = "https"
customDomains = ["{{ .Domain }}", "*.{{ .Domain }}"]
localIP = "127.0.0.1"
localPort = {{ .LocalPort }}

[[proxies]]
name = "{{ .Domain }}-smtp"
type = "tcpmux"
multiplexer = "httpconnect"
customDomains = ["{{ .Domain }}"]
localIP = "127.0.0.1"
localPort = {{ .MailLocalPort }}
